# Generated by Django 3.1.2 on 2020-10-29 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esas', '0002_vahid'),
    ]

    operations = [
        migrations.CreateModel(
            name='mehsul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsulad', models.CharField(max_length=60)),
                ('mehsulkod', models.CharField(blank=True, max_length=50, null=True)),
                ('barkod', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('alisqiymet', models.FloatField()),
                ('satisqiymet', models.FloatField()),
                ('kritiksay', models.FloatField(blank=True, null=True)),
                ('mehsulFoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('qeydtarix', models.DateTimeField(auto_now_add=True)),
                ('boyukolcu', models.ForeignKey(db_column='boyukolcu', on_delete=django.db.models.deletion.DO_NOTHING, related_name='boyukolcu', to='esas.vahid')),
                ('kateqoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esas.mehsulkat')),
                ('kicikolcu', models.ForeignKey(db_column='kicikolcu', on_delete=django.db.models.deletion.DO_NOTHING, related_name='kicikolcu', to='esas.vahid')),
                ('useri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
