# Generated by Django 3.1.2 on 2020-10-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0003_mehsul'),
    ]

    operations = [
        migrations.AddField(
            model_name='mehsul',
            name='stok',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
