# Generated by Django 3.1.2 on 2020-10-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0004_mehsul_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='mehsul',
            name='boyukinkicik',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
