# Generated by Django 3.1.2 on 2020-10-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0005_mehsul_boyukinkicik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mehsulkat',
            name='ktad',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vahid',
            name='vahidad',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
