# Generated by Django 3.1.2 on 2020-10-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0007_auto_20201029_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mehsul',
            name='kateqoriya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esas.mehsulkat'),
        ),
    ]
