# Generated by Django 3.1.2 on 2020-11-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0008_auto_20201029_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehsul',
            name='boyukolcu',
        ),
        migrations.RemoveField(
            model_name='mehsul',
            name='kicikolcu',
        ),
        migrations.AddField(
            model_name='mehsul',
            name='ikinci',
            field=models.ForeignKey(db_column='ikinci', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ikinci', to='esas.vahid'),
        ),
        migrations.AddField(
            model_name='mehsul',
            name='standart',
            field=models.ForeignKey(db_column='standart', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='standart', to='esas.vahid'),
        ),
    ]
