# Generated by Django 3.1.2 on 2020-11-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0009_auto_20201109_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mehsul',
            name='ikinci',
            field=models.ForeignKey(blank=True, db_column='ikinci', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ikinci', to='esas.vahid'),
        ),
        migrations.AlterField(
            model_name='mehsul',
            name='standart',
            field=models.ForeignKey(blank=True, db_column='standart', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='standart', to='esas.vahid'),
        ),
    ]
