# Generated by Django 3.1.2 on 2020-11-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0011_musteri'),
    ]

    operations = [
        migrations.CreateModel(
            name='satis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satissay', models.FloatField()),
                ('endrim', models.FloatField(blank=True, null=True)),
                ('mehsuladi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='esas.mehsul')),
                ('s_musteri', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='esas.musteri')),
                ('vahidi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='esas.vahid')),
            ],
        ),
    ]
