# Generated by Django 3.1.2 on 2020-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0012_satis'),
    ]

    operations = [
        migrations.AddField(
            model_name='satis',
            name='Qaime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
