# Generated by Django 3.1.2 on 2020-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0013_satis_qaime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satis',
            name='Qaime',
            field=models.IntegerField(null=True),
        ),
    ]
