# Generated by Django 3.1.2 on 2020-11-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0015_auto_20201109_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaime',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qaime',
            name='son_odenis_tarixi',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qaime',
            name='toplam_endrim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qaime',
            name='toplam_tutar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
