# Generated by Django 3.1.2 on 2020-11-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0016_auto_20201109_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satis',
            name='s_qaime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esas.qaime'),
        ),
    ]
