# Generated by Django 3.1.2 on 2020-11-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0017_auto_20201109_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaime',
            name='toplam_endrim',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qaime',
            name='toplam_tutar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
