# Generated by Django 3.1.2 on 2020-11-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0019_auto_20201109_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaime',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
