# Generated by Django 3.1.2 on 2020-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0020_auto_20201111_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='satis',
            name='tutar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
