# Generated by Django 3.1.2 on 2020-11-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0021_satis_tutar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satis',
            name='tutar',
        ),
    ]
