# Generated by Django 3.1.2 on 2020-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0023_qaime_odenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='logdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_ad', models.CharField(blank=True, max_length=50, null=True)),
                ('tarix', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
