# Generated by Django 3.1.2 on 2020-11-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esas', '0024_logdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaime',
            name='toplam_endrim_aznle',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='qaime',
            name='toplam_endrim_faizle',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
