# Generated by Django 3.1.2 on 2020-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_bos'),
    ]

    operations = [
        migrations.CreateModel(
            name='meat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
            ],
        ),
    ]
